/**
 * Single source for error codes.
 * Used in API error responses.
 */

export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_USER_DISABLED: "AUTH_USER_DISABLED",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  AGENCY_NOT_FOUND: "AGENCY_NOT_FOUND",
  AGENCY_ALREADY_EXISTS: "AGENCY_ALREADY_EXISTS",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  EMAIL_VERIFICATION_EXPIRED: "EMAIL_VERIFICATION_EXPIRED",
  PASSWORD_RESET_EXPIRED: "PASSWORD_RESET_EXPIRED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_IN_USE: "PLAN_IN_USE",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
